receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # Add exporter for Better Stack:
  otlphttp/betterstack:
    endpoint: "https://s1558406.eu-nbg-2.betterstackdata.com"
    headers:
      Authorization: "Bearer rht9A9qEZFf3hwnuEaxLuami"

processors:
  batch:

service:
  pipelines:
    # Add extra logs and metrics pipelines for Better Stack:
    metrics/betterstack:
      receivers: [otlp] # your metrics receivers
      processors: [batch]
      exporters: [otlphttp/betterstack]
    logs/betterstack:
      receivers: [otlp] # your logs receivers
      processors: [batch]
      exporters: [otlphttp/betterstack]
    traces/betterstack:
      receivers: [otlp] # your traces receivers
      processors: [batch]
      exporters: [otlphttp/betterstack]
