name: Supabase

on:
  push:
    branches:
      - "feat/**"
      - "feature/**"
      - "fix/**"
      - "chore/**"
      - "docs/**"
      - "refactor/**"
      - "perf/**"
      - "test/**"
      - "style/**"

  workflow_dispatch:

jobs:
  test:
    name: Test, lint, and generate backup of database
    runs-on: ubuntu-latest
    environment:
      name: Preview â€“ bytebuzz

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: 2.54.11

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Start Supabase local development setup
        # Temporary fix to avoid migration error https://github.com/supabase/cli/issues/4466
        run: rm -rf supabase/.temp/storage-migration && bun run db:start && rm -rf supabase/.temp/storage-migration && supabase db reset
        # TODO: Remove temporary fix once the issue is fixed
        # run: bun run db:start

      - name: Link to staging project
        # Temporary fix to avoid migration error https://github.com/supabase/cli/issues/4466
        run: rm -rf supabase/.temp/storage-migration && bun run db:link --project-ref $SUPABASE_PROJECT_ID
        # TODO: Remove temporary fix once the issue is fixed
        # run: bun run db:link --project-ref $SUPABASE_PROJECT_ID

      - name: See schemas differences between local and remote
        # Temporary fix to avoid migration error https://github.com/supabase/cli/issues/4466
        run: rm -rf supabase/.temp/storage-migration && bun run db:diff --debug
        # TODO: Remove temporary fix once the issue is fixed
        # run: bun run db:diff --debug

      - name: Run lint
        # Temporary fix to avoid migration error https://github.com/supabase/cli/issues/4466
        run: rm -rf supabase/.temp/storage-migration && bun run db:lint --fail-on error
        # TODO: Remove temporary fix once the issue is fixed
        # run: bun run db:lint --fail-on error

      - name: Run tests
        # Temporary fix to avoid migration error https://github.com/supabase/cli/issues/4466
        run: rm -rf supabase/.temp/storage-migration && bun run db:test
        # TODO: Remove temporary fix once the issue is fixed
        # run: bun run db:test

      - name: Verify generated types are checked in
        # Temporary fix to avoid migration error https://github.com/supabase/cli/issues/4466
        run: |
          rm -rf supabase/.temp/storage-migration && supabase gen types typescript --local > types.gen.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet types.gen.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
        # run: |
        #   supabase gen types typescript --local > types.gen.ts
        #   if ! git diff --ignore-space-at-eol --exit-code --quiet types.gen.ts; then
        #     echo "Detected uncommitted changes after build. See status below:"
        #     git diff
        #     exit 1
        #   fi

      - name: Generate backup
        # Temporary fix to avoid migration error https://github.com/supabase/cli/issues/4466
        run: rm -rf supabase/.temp/storage-migration && bun run db:dump-remote
        # run: bun run db:dump-remote
        # TODO: Remove temporary fix once the issue is fixed
        # run: bun run db:dump-remote

      - name: Upload backup to Vercel Blob
        uses: dartilesm/vercel-blob-action@v2
        with:
          source: "supabase/dump"
          destination: "db-backup-pr/${{ github.ref_name }}"
          read-write-token: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
